---
- hosts: all
  tasks:
        - name: install http
          package:
                name: "httpd"
                state: present
        
        - name: install php
          package:
                name: "php"
                state: present
        
        - name: install http
          package:
                name: "git"
                state: present

        - name: start and enable service 
          service:
                name: "httpd"
                state: started
                enabled: yes
